"""
Django settings for telusko project.

Generated by 'django-admin startproject' using Django 3.1.2.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import cloudinary
import dj_database_url

# Load .env file
load_dotenv()

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://emadventure.com',
    'http://localhost:8000',
]

# SECURITY
SECRET_KEY = os.getenv('SECRET_KEY', 'aliwy-w)qwg1##ln(ig)j$s6oz#vp4zq4hm11ao$j9b!h6k*8x')
DEBUG = False
ALLOWED_HOSTS = ["*"]

# APPLICATIONS
INSTALLED_APPS = [
    'jazzmin',
    'travello.apps.TravelloConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    "django_countries",
]

# MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise kwa static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT URL
ROOT_URLCONF = 'telusko.urls'

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "travello.context_processors.booking_form_processor",
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'telusko.wsgi.application'

# ✅ DATABASE CONFIGURATION (PostgreSQL - Supabase)
# DATABASE_URL = os.getenv(
#     "DATABASE_URL",
#     "postgresql://postgres:NyumbaChap@db.qcyyazosbftensualamm.supabase.co:5432/postgres"
# )

# DATABASES = {
#     'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
# }




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres.qcyyazosbftensualamm',  
        'PASSWORD': 'NyumbaChap', 
        'HOST': 'aws-1-us-east-2.pooler.supabase.com', 
        'PORT': '5432',
        'OPTIONS': {'sslmode': 'require'},  # hii inaruhusu SSL


    }
}



# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Dar_es_Salaam'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# STATIC & MEDIA FILES
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# CLOUDINARY SETTINGS
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET')
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET')
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = f"https://res.cloudinary.com/{os.getenv('CLOUDINARY_CLOUD_NAME')}/"

# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    "site_title": "Kilindo Tours and Safaris Admin",
    "site_header": "Kilindo Tours and Safaris Dashboard",
    "welcome_sign": "Karibu kwenye Dashboard  Kilindo Tours and Safaris",
    "copyright": "© 2025 Kilindo Tours and Safaris",
    "show_sidebar": True,
    "navigation_expanded": True,
    "user_avatar": None,
    "search_model": "auth.User",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "Kilindo Tours and Safaris"},
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "show_ui_builder": True,
}

# AUTO FIELD
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
